### ISSUE TITLE
Improve favicon in dark mode

### ISSUE THREAD

**Issue by fpellet** [adminerevo/adminerevo#104]
Hello,

Thanks for this fork :)
The favicon has changed compared to adminer, and in the browser's dark mode, the icon is not visible.
Would it be possible to use the old icon or to put this icon on a white background?

**Comment by LionelLaffineur** [comment]
Hi @fpellet, thanks for reporting this.  I have put white background icon for the moment.  But in an ideal world, I would like two different favicons : 1 for light mode and 1 for dark mode.
We'll see when one has time to do it.
Regards,
L.

**Comment by fpellet** [comment]
Thank you!

The mix of the two colours seems good to me in any case to adapt to the different browser templates which can go beyond dark mode.
