### ISSUE TITLE
Use adminer for automated backup of database

### ISSUE THREAD

**Issue by Letme** [adminerevo/adminerevo#105]
I want to use Adminer's export functionality to perform regular database backups of my database. I think the Export functionality is a decent candidate, but looking at the form it sends `POST` request, so I was wondering if there is a way to perform an Export through command line (or for example using curl to download it from something like `/?server=database&username=blah&db=exampledb&dump=gzip ...`).

I also assumed I could restore the database via Adminer Import command (I can download backup file and place it as `adminer.sql.gz` next to the adminer.php file and then execute something like: `/?server=database&username=blah&db=exampledb&import=adminer.sql.gz` to restore?

Any ideas would be welcome, as I rather utilize Adminer than to install a new tool

**Comment by Letme** [comment]
Yes, the reason is simple. I have php container and database container and the password to access database is only available in php container. Php container does not have `mysqldump` command. What I now do, is I copy/generate `.my.cnf` file from php container to database container and then run the database backup from it like you mentioned. But I wanted a bit more straight usage directly from php container.

**Comment by devinemke** [comment]
ah. so then mySQL resides on the other (non-PHP) container? and thus it is not possible to run **mysqldump** via PHP's **[shell_exec()](https://www.php.net/manual/en/function.shell-exec.php)** function?

Probably getting overly complicated, but could you use PHP to SSH into the mySQL container? and then be able to run whatever mySQL CLI that you need? not very elegant, but might work.

**Comment by Letme** [comment]
Yes, that is what is also the possibility, but again because of how mqsqldump is invoked, I cannot work with arguments to the function, but I need to create that file. So overall it seems that I would want to limit the amount of time that file is created/on disk and I would also not like to open SSH to the MySQL container to avoid opening an attack surface. So far using Kubernetes API I am able to perform these tasks, but somehow I thought it would be easier through Adminer.

I guess the simple answer is no, there are better existing options available. Thanks for the discussion.
