### ISSUE TITLE
Use select instead of radio for enum columns

### ISSUE THREAD

**Issue by nitodico** [adminerevo/adminerevo#108]
Enum columns should use a `select > option` input tag instead of a bunch of `input radio` labels, specially if you are using an enum columns with a bunch of options... also they are more readable IMO

Example:
![image](https://github.com/adminerevo/adminerevo/assets/49000973/b63e8c2f-c09a-482f-a799-5a30569c47b5)

**Comment by LionelLaffineur** [comment]
Dear @nitodico, it is indeed not very user-friendly.  Thanks for reporting this.
I will try to do something ... or if someone wants to propose a PR, it is welcome.

**Comment by LionelLaffineur** [comment]
There was a plugin for that.  But I really find the radios so much unfriendly to use that I made it default and deprecated the plugin.
I left the plugin in the code to avoid issues for setups using it, however, it will be removed in the future.
