### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by sixgodfan** [adminerevo/adminerevo#110]
php8.3，mysql5.7，mysqli，adminerevo 4.8.3
Warning: Trying to access array offset on null in adminerevo.php on line 1491
Warning: Trying to access array offset on null in adminerevo.php on line 1517
1818

**Comment by 49-3** [comment]
i got the same issue with 1812 and 1813 too
maybe someone have a fix ?

**Comment by alxndr-w** [comment]
Me too

**Comment by alxndr-w** [comment]
closed with https://github.com/adminerevo/adminerevo/releases/tag/v4.8.4
