### ISSUE TITLE
Make border softer and more beautiful for buttons and input fields

### ISSUE THREAD

**Issue by OmlineEditor** [adminerevo/adminerevo#111]
you have made the border for elements that can be clicked and edited very large and dark. It is very unusual to look at these elements, they look very rough. you can remove such a thick and large frame and return it as it was in the old version from: vrana/adminer

compare the two versions:

Old version vrana/adminer 4.8.1 ↓
![1old](https://github.com/adminerevo/adminerevo/assets/13348933/9c053614-2f6c-4a9d-9518-5c34f95d6dc3)

New version  4.8.3 ↓
![2new](https://github.com/adminerevo/adminerevo/assets/13348933/83402dff-cc17-4f12-9ff2-05ccaefe8a26)

**Comment by nitodico** [comment]
Doesn't this affect CSS templates? if we add rounded borders to default CSS style, it could affect to all CSS themes

**Comment by OmlineEditor** [comment]
> Doesn't this affect CSS templates? if we add rounded borders to default CSS style, it could affect to all CSS themes

you don't need to add anything, you need to return it as it was before. Now the frame is very thick and ugly, it is wide. leave the corners rounded and return the thickness of the frames.
