### ISSUE TITLE
Undefined property: stdClass::$table in adminer.php on line 1523 

### ISSUE THREAD

**Issue by OmlineEditor** [adminerevo/adminerevo#116]
the error occurs if you search for data in a table that has an IP address type. here is a detailed way to see this error: https://github.com/adminerevo/adminerevo/issues/115

**Comment by mckaygerhard** [comment]
duplicate of #146  related to #115

**Comment by mckaygerhard** [comment]
well i tested last version  https://github.com/adminerevo/adminerevo/releases/tag/v4.8.4  and i do not see any error with postgresql 9.6 just show directly the export plain text in SQL

![image](https://github.com/adminerevo/adminerevo/assets/1571724/24ba55ab-dfec-4656-bdfc-9a7b2e03d3a0)

**Comment by OmlineEditor** [comment]
the error disappeared, perhaps it was still a problem on the provider’s server.

**Comment by mckaygerhard** [comment]
you said "just dissapears".. umm @OmlineEditor started the issue but later just dissapear.. based on their activity.. seems its a fake user to open issues to give importance.. it opens issues in russian and chinesse langs but once opened does not reply anymore

**Comment by OmlineEditor** [comment]
> you said "just dissapears".. umm @OmlineEditor started the issue but later just dissapear.. based on their activity.. seems its a fake user to open issues to give importance.. it opens issues in russian and chinesse langs but once opened does not reply anymore

there is no point in writing anything if my answer does not affect anything
