### ISSUE TITLE
PHP 8.3

### ISSUE THREAD

**Issue by stempora** [adminerevo/adminerevo#118]
Hello,

There are a lot of warnings when running on php 8.3. 

Is there any plan to make it fully compatible ?

**Comment by mckaygerhard** [comment]
i was testing and currently only few warnings are happened.. there is some issues with column filtering..  by example: Undefined array key "UPPER(`LOGGED`)" when try to use upper functions on select filters

![image](https://github.com/adminerevo/adminerevo/assets/1571724/744b534a-4e31-48b7-9a8c-6ab9e1330d69)
![image](https://github.com/adminerevo/adminerevo/assets/1571724/d782080d-fb97-41e5-ace6-7d6c2a4031e5)

**Comment by alxndr-w** [comment]
closed with https://github.com/adminerevo/adminerevo/releases/tag/v4.8.4
