### ISSUE TITLE
AdminerEvo Docker image request

### ISSUE THREAD

**Issue by SilentJMA** [adminerevo/adminerevo#119]
Hi Team,

Can we have a docker image available with documentation?

**Comment by holygekko** [comment]
would love to see that as well, preferably on docker hub

**Comment by epicwhale** [comment]
+1 to this

**Comment by epicwhale** [comment]
Especially if it was dropin replacement for https://hub.docker.com/_/adminer - it would really easy to transition / try this out with least friction!

**Comment by jonbirge** [comment]
agreed. anybody know how to find the Dockerfile for the original adminer docker image? that would be the obvious place to start.

**Comment by shyim** [comment]
I made one lol, works exactly the same as adminer official image. Do you want to take over to this org, I can still maintain it
https://github.com/shyim/adminerevo-docker
https://hub.docker.com/r/shyim/adminerevo

**Comment by LionelLaffineur** [comment]
Thanks for following this new repo in docker !

**Comment by SilentJMA** [comment]
What do you think @LionelLaffineur regarding @shyim suggestion?

**Comment by LionelLaffineur** [comment]
I have never created dockers.  If you would like to continue maintaining it, I can however take over the org.
I can however learn a little about how to create a new docker if needed; but it's not a first priority, I miss time to do everything and prefer to get some help.

**Comment by shyim** [comment]
Sure. I can do that :)

**Comment by alxndr-w** [comment]
Duplicate #22
