### ISSUE TITLE
Search default column

### ISSUE THREAD

**Issue by duzenko** [adminerevo/adminerevo#124]
I'm overall very happy with the original 4.8.1 version but there's one particular thing I'd like to see improved

1. Go to any table
2. Click 'select data'
3. Click 'search'
4. Click 'anywhere' and choose the PK column
5. Click on the search text input
6. Press Enter

Would you agree that step 4 should be automatic? I.e. the search column should be the PK column by default?
Currently the default mode is search all columns, which I guess makes sense for smaller tables, but IRL most tables are rather big and we most often search by PK id anyway.

**Comment by duzenko** [comment]
Or , alternatively, add a tiny link next to 'Search' that will do the same thing (expand the groupbox) but switch the column dropdown to the PK column

**Comment by LionelLaffineur** [comment]
@duzenko, thanks for sharing that idea with the community.
Anyway, I'm not sure this kind of specific behavior is something that should be generic for everybody.
I could well see that being done by a plugin.
