### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'appendChild') at verifyVersion

### ISSUE THREAD

**Issue by adrianbj** [adminerevo/adminerevo#128]
Thanks all for your dedication to keep this great tool alive.

I am seeing the noted JS error and from what I can tell, it's due to the [removal](https://github.com/adminerevo/adminerevo/commit/8b5390076d53ce29136191b52e49597ce26b0b40) of this line: 
```
<a href="https://www.adminer.org/#download"<?php echo target_blank(); ?> id="version"><?php echo (version_compare($VERSION, $_COOKIE["adminer_version"]) < 0 ? h($_COOKIE["adminer_version"]) : ""); ?></a>
```
This causes the error, because of `qs('#version').appendChild(iframe);` in the `verifyVersion()` function: https://github.com/adminerevo/adminerevo/blob/d5ccd05355e4a7aed0e10193a853521a13f10914/adminer/static/functions.js#L124

Now there is no element with an id = "version".

Also note that `verifyVersion()` still references adminer.org here https://github.com/adminerevo/adminerevo/blob/d5ccd05355e4a7aed0e10193a853521a13f10914/adminer/static/functions.js#L105 and here https://github.com/adminerevo/adminerevo/blob/d5ccd05355e4a7aed0e10193a853521a13f10914/adminer/static/functions.js#L114

but of course https://www.adminerevo.org/version/ doesn't actually do what it needs to yet either, so a few things need to happen to get this working.

Perhaps the reason you removed that is because Material for MkDocs won't let you make https://www.adminerevo.org/version/ work as needed?

On a related note, the `adminer_version` cookie is being set to `0`

Please let me know if there is any other info I can provide.

Thanks!

**Comment by LionelLaffineur** [comment]
Hi @adrianbj, thanks for this very precise information.  Would you like to propose a PR to fix the issues ?

**Comment by adrianbj** [comment]
@LionelLaffineur - I thought about putting together a PR, but the solution really comes down to whether you can make https://www.adminerevo.org/version/ return the version number like https://www.adminer.org/version/ currently does.

I suppose I could point to https://raw.githubusercontent.com/adminerevo/adminerevo/main/adminer/include/version.inc.php and parse out the version number from that, but the approach used previously is more complicated than that with a `postMessage()` - take a look at: `view-source:https://www.adminer.org/version/?current=4.8.0` - but do we need it to be that complicated? I don't see where the signature from that `postMessage()` is actually used - it looks like only the `version` is parsed - https://github.com/adminerevo/adminerevo/blob/d5ccd05355e4a7aed0e10193a853521a13f10914/adminer/static/functions.js#L102

So, just to clarify - I am happy to help with a PR, but would need to know what you you are willing to do in terms of setting up that https://www.adminerevo.org/version/ page, or if you think parsing the content of version.inc.php would be an OK alternative.

**Comment by LionelLaffineur** [comment]
You cannot link to https://raw.githubusercontent.com/adminerevo/adminerevo/main/adminer/include/version.inc.php, it will be most of the time one release higher -dev.
There is something I don't get right now, what is the goal of this ?

**Comment by adrianbj** [comment]
> it will be most of the time one release higher -dev

Of course - sorry, didn't notice that initially.

> what is the goal of this

There are two goals - one is to get rid of the JS error - that would be an easy fix, but I was thinking the better approach would be to restore the original intended functionality which is to check the current released version and change the version number in the interface to highlight that the installed version is out of date and replace it with a link to the download page to get the new version.

**Comment by adrianbj** [comment]
Thanks - I'll take a look at putting together a PR in the next couple of days.

Obviously your new version won't work like: `view-source:https://www.adminer.org/version/?current=4.8.0` so will obviously need to change the way things are handled, but hopefully shouldn't be an issue.

Actually, maybe I could parse this: https://api.github.com/repos/adminerevo/adminerevo/releases/latest rather than you needing to maintain that subdomain? As long as you continue to tag releases in that `v4.8.3` I can use the `name` or `tag_name` properties from the github JSON.

**Comment by adrianbj** [comment]
PR available here: https://github.com/adminerevo/adminerevo/pull/129
