### ISSUE TITLE
default sort by first column descending

### ISSUE THREAD

**Issue by OmlineEditor** [adminerevo/adminerevo#130]
The most common action I do when viewing tables is viewing the latest records in the table.

To view the latest records in the table I need to do the following:
- open table
- select the first column to sort
- select sorting in descending order
- click apply to sort

I ask you to automate the process by default and sort when opening a table by the first column and in descending order.
I just open the table and everything is already sorted there by default, it will be easier to work this way

**Comment by OmlineEditor** [comment]
if necessary, here is the command for PostgreSQL to get the name of the first column
```
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'specify_the_name_of_the_table_here'
ORDER BY ordinal_position
LIMIT 1;
```

**Comment by LionelLaffineur** [comment]
Dear @OmlineEditor, it doesn't look to be a good idea to change the default behavior of Adminer, used by many users daily for a specific behavior and force everyone to work like you do.  Don't you think this is typically a customization you should do via a plugin ?  Personally, I do.
On top of that, Adminer supports several different database engines, which makes it a very bad idea to access information schema of a specific engine knowing all of them have different information schemas.
Regards,
L.

**Comment by OmlineEditor** [comment]
I can write a plugin myself, but I need help. I need an example of a similar plugin or detailed documentation to understand what needs to be done. Could you help me?
