### ISSUE TITLE
Syntax error in adminerevo 4.8.4

### ISSUE THREAD

**Issue by AgentSmith0** [adminerevo/adminerevo#133]
I am using PHP version 8.3.4 and I get the following error message when running adminer:
`Parse error: syntax error, unexpected token "echo", expecting "," or ";" in adminer-4.8.4.php on line 1273`

The editor works fine.

**Comment by adrianbj** [comment]
Sorry about that. PR to fix it: https://github.com/adminerevo/adminerevo/pull/134

**Comment by LionelLaffineur** [comment]
@adrianbj : it's me ... I added a title on the a tag and forgot the semi-colon.
I have re-created the release and the downloads.
