### ISSUE TITLE
Syntax error, unexpected '?' with PHP 5.6

### ISSUE THREAD

**Issue by francoisjacquet** [adminerevo/adminerevo#136]
Hello,

Thank you for releasing adminerevo 4.8.4 :)

I have tested it with PHP 5.6.40 (had v4.8.2 previously)

Here is the error message:
```bash
PHP message: PHP Parse error:  syntax error, unexpected '?' in /adminer-4.8.4.php on line 65
```

**Comment by adrianbj** [comment]
Looks like it's the null coalescing operator on this line: https://github.com/adminerevo/adminerevo/blob/2eba0b515455ba38973d4966354df0f45a8abdfd/adminer/include/functions.inc.php#L502

Looks like lots of these were used for 8.3 deprecation warning fixes: https://github.com/search?q=repo%3Aadminerevo%2Fadminerevo%20%22%3F%3F%22&type=code

I suppose the big picture question is whether PHP 5.x is going to be supported going forward.

**Comment by LionelLaffineur** [comment]
What is the best option ?
- support PHP5.6 but not 8.3; PHP 8.3 will be deprecated 23 Nov 2026
- support PHP8.3 but not 5.6; PHP 5.6 is deprecated since 31 Dec 2018
Knowing it seems difficult to have both, which one seems to be the best choice ?
I'm sorry for 5.6 users but I'm looking forward and not backwards.
Perhaps is it time to upgrade PHP ?

**Comment by LionelLaffineur** [comment]
If you have a PHP5.6 to test and wish to make it compatible, I can accept a PR for that.
I personally don't have a PHP5.6 setup, and even if I could find a docker, I don't really have time to invest in that topic.  I think there are more important topics than keeping compatible with a very old PHP.  (again sorry for PHP5.6 users, and again perhaps time to upgarde?)

**Comment by adrianbj** [comment]
@LionelLaffineur - I don't have a 5.6 to test with at the moment (and like @LionelLaffineur not really interested in setting one up), but it sounds like you are in a good position to confirm that my `isset` version above works (it should) and submit a PR.

**Comment by francoisjacquet** [comment]
Hello @adrianbj 

Yes, I confirm `isset( $var ) ? $var : null` is the equivalent of the null coalesce operator.

Please understand I limit myself to reporting errors here, I am already busy with other projects, sorry :(

As already mentioned, I'm fine with you dropping support for PHP5.6 and use an old version. The purpose of my issue was just to report this version is not compatible with PHP5.6 anymore.

**Comment by nevergone** [comment]
I think that as long as compatibility can be maintained, it is advisable to strive for this. The "isset()" is great solution.

**Comment by LionelLaffineur** [comment]
@francoisjacquet, if I would do the fix to remove the null coalesce in a branch, would you test it ?  I have no PHP5.6 by the hand and am not really interested in setting it up.

**Comment by mckaygerhard** [comment]
check #83 i detailed the problem there .. and there is a fork at https://github.com/adminerevo/adminerevo/issues/83#issuecomment-2581327296

issue described also at https://github.com/adminerevo/adminerevo/discussions/135#discussioncomment-11789958
