### ISSUE TITLE
Possible to generate a db dump from PHP

### ISSUE THREAD

**Issue by bruce-redpin** [adminerevo/adminerevo#143]
Hi,

Is there anyway to start a DB dump from a PHP file? Want to be able to perform auto local backups of the DB from within Wordpress.

**Comment by Letme** [comment]
There is a way to export whole database (all tables) with Export command, but not programmatically through adminer (lets say with curl).

There is a big discussion here: https://github.com/adminerevo/adminerevo/issues/105
