### ISSUE TITLE
MySQL export incomplete

### ISSUE THREAD

**Issue by shionryuu** [adminerevo/adminerevo#144]
My database has more than 1000 tables, but I can only export part of it.

```sql
> select count(*) as totalnumberoftables from information_schema.tables where table_schema = 'dbname';
+---------------------+
| totalnumberoftables |
+---------------------+
|                1015 |
+---------------------+
1 row in set (0.00 sec)
```

select all tables and export `dbname.sql` using [adminerevo](https://github.com/adminerevo/adminerevo)

```bash
$ cat dbname.sql | grep 'CREATE TABLE' | wc -l
992
```

Version `Ubuntu 24.04`, `AdminerEvo 4.8.4`, `MySQL version: 8.0.36-2ubuntu3 through PHP extension MySQLi`

**Comment by mckaygerhard** [comment]
This is a limitation of the php settings and your server hosting configuration.. 

issues must be close is there is no propert huge configuration for huge data in such server..
