### ISSUE TITLE
Php 8.3.8 warning (Trying to access array offset on null in /srv/www/adminerevo/adminer/indexes.inc.php on line 33 129 and 130)

### ISSUE THREAD

**Issue by RoyBellingan** [adminerevo/adminerevo#154]
same as #153

# The other bug are 

https://github.com/adminerevo/adminerevo/blob/main/adminer/indexes.inc.php#L33

here we can be fancy and do that, but I do not remember what is the minimum supported version of adminer atm...
```Php
$desc = $index["descs"][$key] ?? null;
```
So we should do
```Php
$desc = isset($index["descs"][$key]) ? $index["descs"][$key] : null;
```

Replace https://github.com/adminerevo/adminerevo/blob/main/adminer/indexes.inc.php#L129
with
```Php
			$ilk = "";
			if(isset($index["lengths"][$key])){
				$ilk = h($index["lengths"][$key]);
			}
			echo ($jush == "sql" || $jush == "mssql" ? "<input type='number' name='indexes[$j][lengths][$i]' class='size' value='" . $ilk . "' title='" . lang('Length') . "'>" : "");

```

And https://github.com/adminerevo/adminerevo/blob/main/adminer/indexes.inc.php#L130

```Php
			$idk = "";
			if(isset($index["descs"][$key])){
				$idk = $index["descs"][$key];
			}
			echo (support("descidx") ? checkbox("indexes[$j][descs][$i]", 1, $idk, lang('descending')) : "");
```

**Comment by LionelLaffineur** [comment]
Fixed here: https://github.com/adminerevo/adminerevo/commit/91aff545e9d35a1179ad81700512b18e8296d8e1.

**Comment by mckaygerhard** [comment]
the commit 6283155 and 385112a rollback the commit  91aff545 and means this issue must be reopened
