### ISSUE TITLE
Adminer Evo export feature generates wrong SQL syntax on auto increment ID

### ISSUE THREAD

**Issue by GottfriedCP** [adminerevo/adminerevo#157]
When exporting tables into SQL file using Adminer, the SQL syntax like below is generated. 

Look at the `id` column definition. That is wrong and causes error.

```
CREATE TABLE "public"."auth_group" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(150) NOT NULL,
    CONSTRAINT "auth_group_name_key" UNIQUE ("name"),
    CONSTRAINT "auth_group_pkey" PRIMARY KEY ("id")
) WITH (oids = false);
```

The correct syntax is:

```
"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL
```

**Comment by LionelLaffineur** [comment]
Hi @GottfriedCP,

Can you please add some details on how to reproduce the issue ?

Regards,
L.

**Comment by codewizard13** [comment]
@GottfriedCP I'm having issues also. Did you ever get this solved?

**Comment by GottfriedCP** [comment]
Another Github user @peterpp with his forked Adminer accommodated my issue and released it

https://github.com/pematon/adminer

I will try it

**Comment by adrianbj** [comment]
Not sure this should be closed if it's still an issue here. 

OT but it seems a shame that we might end up with two competing forks of Adminer.

**Comment by peterpp** [comment]
It should not be closed. @LionelLaffineur Feel free to cherry pick this fix: https://github.com/pematon/adminer/commit/353cd452a38cf4d0ce6ee5e04992f9249742f6ca

> OT but it seems a shame that we might end up with two competing forks of Adminer.

I'm sorry for that, I have some reasons to stick with my own fork.
