### ISSUE TITLE
Release 4.8.2

### ISSUE THREAD

**Issue by HLFH** [adminerevo/adminerevo#16]
As the master branch of `adminerevo` is currently 21 commits ahead of vrana:master, could we maybe release 4.8.2?
Even if the commits are minor updates, it would be quite symbolic to submit a new release after two years without releases.

**Comment by LionelLaffineur** [comment]
Sorry, I overlooked your topic.  I can tell you that it is planned to do a minor release with little changes then to go to a major one later with more.  Thanks for your interest in the project !

**Comment by lukastribus** [comment]
It would be great to provide the compiled editor and adminer php files in the Github release page, as opposed to just the source tarball, this way adminerevo is ready for use (like the original project).

**Comment by LionelLaffineur** [comment]
v4.8.2 has been released.  Have fun with it and feel free to report any issue.

**Comment by LionelLaffineur** [comment]
> It would be great to provide the compiled editor and adminer php files in the Github release page, as opposed to just the source tarball, this way adminerevo is ready for use (like the original project).

Dear @lukastribus, it is a really good idea, a first time for me ... The compiled file adminer-4.3.2.php has been added.
Thanks for the suggestion!

**Comment by HLFH** [comment]
@LionelLaffineur Thanks for the release!
