### ISSUE TITLE
Favicon edit

### ISSUE THREAD

**Issue by icyz** [adminerevo/adminerevo#169]
Hi,
How can I change the favicon of Adminerevo?

This: 
![image](https://github.com/adminerevo/adminerevo/assets/1923633/f2c8a469-05ca-4c01-a37b-01c6b94aee90)

**Comment by LionelLaffineur** [comment]
Hi @icyz, it is not planned to give the ability to change the favicon.  We could think about it, but it's not a priority right away since we miss hands to proceed with all pending tasks.

**Comment by adrianbj** [comment]
@icyz - you can probably modify that using  name()
https://www.adminer.org/en/extension/
