### ISSUE TITLE
Project direction and nature, just a fork for stability and update or new one?

### ISSUE THREAD

**Issue by mckaygerhard** [adminerevo/adminerevo#17]
Hi @LionelLaffineur  seem you manages this, as the author seems do no post a conclusive response and people suggest to continue.. there are several reason that point this project as new one event just a fork:

1. Author is not active over the development and **do not have a team managing the repository, you should not repeat same error,** you must promoted a person to sencod you and/or build a team for: https://github.com/adminerevo/adminerevo/issues/3#issuecomment-1567324554
2. This repo/project comment suggest to continue without him but, **would mean that it would branch out so much that it would differentiate significativelly from original**, and it would no longer be the same.
3. The ideas for changes began to rain when we have not yet resolved all the Merge REquests that are pending, that is, **we have not stabilized what is important (those MRs) and there are already strong changes proposed** like the moving to bootstrap: https://github.com/adminerevo/adminerevo/discussions/5

So then this **looks more than a complete new directio more thant just a fork to mantain the project security and updates**

**Comment by mckaygerhard** [comment]
**NOTE** i always think about ODBC cos with just one direction you can support all the databases, ODBC its just an standard.. maybe a little related brother project named adminerodbc with only basic standar functions could be great under same adminerevo organization. My 50c contribution.

**Comment by LionelLaffineur** [comment]
> Hi @LionelLaffineur  seem you manages this, as the author seems do no post a conclusive response and people suggest to continue.. there are several reason that point this project as new one event just a fork:
Hi @mckaygerhard 
> 
> 1. Author is not active over the development and **do not have a team managing the repository, you should not repeat same error,** you must promoted a person to sencod you and/or build a team for: https://github.com/adminerevo/adminerevo/issues/3#issuecomment-1567324554
This is indeed something that was not left aside in the decision to continue the project. Even if they don't post a lot, we are three administrators on the organisation and repo. 
> 2. This repo/project comment suggest to continue without him but, **would mean that it would branch out so much that it would differentiate significativelly from original**, and it would no longer be the same.
The original developer is invited to join the project. I would appreciatehis help/feedback.
> 3. The ideas for changes began to rain when we have not yet resolved all the Merge REquests that are pending, that is, **we have not stabilized what is important (those MRs) and there are already strong changes proposed** like the moving to bootstrap: https://github.com/adminerevo/adminerevo/discussions/5
It is not the idea to take a completely differentdirection, but it's also not the idea to not evoluate. We are looking towards an in-between.
I made the rain of ideas myself to take the temperature about my ideas, and also about the interest of the community. Not all of them will get alive, the bootstrap one was closed quite quickly.
> 
> So then this **looks more than a complete new directio more thant just a fork to mantain the project security and updates**
It's not. However, your interest and suggestions are very appreciated. Feel free to react to other posts (now and later on the upcoming ones).

**Comment by LionelLaffineur** [comment]
Waouw, ODBC ! It makes me jump back in the past. 've been using it in the late 90th, early 2000th. But it's so far away that I would not have thought it still exists !
I won't promise anything else then discussing it with the other team members and evaluate it.
Thanks for this input and the50 cents. Please post any other 50 cents 😉

**Comment by mckaygerhard** [comment]
> Waouw, ODBC ! It makes me jump back in the past. 've been using it in the late 90th, early 2000th. But it's so far away that I would not have thought it still exists ! I won't promise anything else then discussing it with the other team members and evaluate it. Thanks for this input and the50 cents. Please post any other 50 cents wink

err men.. in your response.. XD :laughing:  you quoted both cited and your reponse XD :laughing:  but dont worry i read you (deducting the lines je je)

**Comment by mckaygerhard** [comment]
due the formt i will repost here to mantain in context who check this issue:

about having a team .. Lionel cites in the lines 
>_.. won't promise anything else then discussing it with the other team members and evaluate i.._

and we have a namespace organization names adminerevo so for all people there's a team behing this project

About project direction or fork:

> It's not. However, your interest and suggestions are very appreciated. Feel free to react to other posts..

About the original project and author:

> The original developer is invited to join the project. I would appreciatehis help/feedback.

About the team it selft:

>.. we are three administrators on the organisation and repo...

About the interes in the project:

>  .. made the rain of ideas myself to take the temperature .. and also about the interest of the community. Not all of them will get alive.. 

@LionelLaffineur Thanks for all clarifications, i'll close thi issue but open a new one and left that openes:  **i guess a limited web page made with github io web service will help others to promote interest in the project..**
