### ISSUE TITLE
[pgsql] Warning: Undefined property: stdClass::$table

### ISSUE THREAD

**Issue by olegbaturin** [adminerevo/adminerevo#179]
pgsql server_version 15.1
PHP Version 8.0.17
Windows Server 2019

![image](https://github.com/user-attachments/assets/a3bed5a6-466a-43d4-a7e9-08f0ba19757e)

```
stdClass Object
(
    [orgtable] => app
    [name] => id1
    [orgname] => id1
    [type] => int4
    [charsetnr] => 0
)
```

related #146

**Comment by MisterDuval** [comment]
fixed there isn't it ? https://github.com/adminerevo/adminerevo/pull/177
