### ISSUE TITLE
Missing SQL and Import links on MariaDB

### ISSUE THREAD

**Issue by NoxArt** [adminerevo/adminerevo#212]
Hello,
![image](https://github.com/user-attachments/assets/85451098-9a3f-4e44-a9e1-9cd9ac2e7e13)
I think there should be Create SQL and Import links here as well ... on previous Adminer 4.7 they were there and &sql= and &import= work both to access the page and use its functionality

I'm guessing the issue might be with the regex? But it will probably be better if someone more familiar with it would look at it
https://github.com/adminerevo/adminerevo/blob/1ae175a1dbd3e875c7edb939eadbd869487cf4e5/adminer/drivers/mysql.inc.php#L1113

Our reported version string is "10.5.21-MariaDB-0+deb11u1"

Thank you

**Comment by mckaygerhard** [comment]
hi can you try by using a C locale? @NoxArt ? i cant find your reference, i already uses in the past the same version and older ones also of that DBMS

**Comment by NoxArt** [comment]
I'm sorry, don't know what you mean by "C" locale, I tried English but no change

**Comment by mckaygerhard** [comment]
> mean by "C" locale, I tried English but no change

for the sack of demons and aliens.. at least do you search for a while?

![image](https://github.com/user-attachments/assets/0c6dda72-34f1-4542-afc5-57b65c546a8c)

## about the isssue

i dont know if that is the problem, **but i cannot reproduce your issue**, of course i do not set any **LOCALE** and "C" is a standar locale when there is no definition

**my suspicions were that having a string in another language that contained strange characters could influence the regular expression** BUT after check the code seems that does not make any sense, sorry

**Comment by NoxArt** [comment]
I simply didn't know what kind of locale are you talking about and you immediately choose to be hostile, ok then

**Comment by peterpp** [comment]
@NoxArt Did you try to disable custom design or plugins if you use some? It looks like you use "ng9" design, but that "Vytvořit tabulku" link looks quite strange. My guess is that your missing links are hidden under the header.

![387598316-85451098-9a3f-4e44-a9e1-9cd9ac2e7e13](https://github.com/user-attachments/assets/ac3b419c-de56-45b1-b445-e8c478103deb)

**Comment by NoxArt** [comment]
Thank you for reply

1/ setlocale(LC_CTYPE, 'C'); didn't have any effect
2/ disabling all customizations and plugins didn't have any effect
3/ if I go to Browser Console and delete the top bar element the links are not below it either
![image](https://github.com/user-attachments/assets/b14dd865-a43a-4afb-8603-eac48c4588fa)

**Comment by peterpp** [comment]
So my second guess is that those links are stacked below the "Create table" button. You still have a custom design on the screenshot. Can you turn it off?

**Comment by NoxArt** [comment]
You're right, I thought the styling is part of the plugins, but it seems it automatically loads adminer.css if it's there

So this is now resolved, thank you very much, sorry for bothering
