### ISSUE TITLE
hide private data from the URL address

### ISSUE THREAD

**Issue by OmlineEditor** [adminerevo/adminerevo#24]
I ask you to change the logic of the script and not to transmit the most important data in the address line.
I ask you to remove from them the address of the SQL server, the name of the database, the user name.

When you open the program, all the data is in the address bar and can be intercepted, I ask you to store it in the PHP session and transmit it only through a POST request, not through a GET request.

This will increase the security and user confidence in the new version

**Comment by nitodico** [comment]
This could limit the possibility to store it as bookmark or share the same static link with a team

**Comment by OmlineEditor** [comment]
it's either security or convenience. if a person works alone, he well needs to bookmark or share with someone. I don't need to share links and bookmarks with someone, so I look at the problems from my side. If you manage to implement the option of choosing a job or everything is hidden or convenient, it will be much more convenient.

**Comment by LionelLaffineur** [comment]
Well, hiding parameters from the URL doesn't increase the security. Every browser has tools to see the request and response where POST parameters are listed.

I think choosing between POST and GET shouldn't be made upon security but well if it is user input or contextual information (ie).

**Comment by gerryd** [comment]
> This could limit the possibility to store it as bookmark or share the same static link with a team

I think this is indeed the most compelling argument to keep it the way it is. Indeed, removing this possibility would be a step back.

> I think choosing between POST and GET shouldn't be made upon security but well if it is user input or contextual information (ie).

While I agree with the sentiment, it is not entirely true. You wouldn't for example transmit a password via a GET parameter, for multiple reasons.

Summary: I don't think this needs changing from the way it is currently.

**Comment by OmlineEditor** [comment]
well, let's leave it as it is without changes, let's hope it won't bring problems
