### ISSUE TITLE
Copy to clipboard vs truncated queries

### ISSUE THREAD

**Issue by LionelLaffineur** [adminerevo/adminerevo#35]
In case of truncated queries (...), the truncated query is copied to the clipboard.  It should, of course, be the complete query that should be copied to the clipboard.

**Comment by smuuf** [comment]
It's possible that the query would have several megabytes. It's also possible that there would be tens/hundreds of such giant queries on one page (if you're referring, for example, to the process list). 

So I think there should be a limit to the size of what can be copied - or there could also be another additional mechanism for this - for example storing the listed queries in some sort of _short-lived_ server-side cache as separate `.sql.tmp` files and giving the user the ability to download those files.

**Comment by LionelLaffineur** [comment]
Dear @smuuf, I'm wondering if there is not a misunderstanding: the copy to clipboard feature is copying the query into the clipboard and not the data resulting of the execution of the query.  This would be an export to clipboard.
Regards,
L.

**Comment by smuuf** [comment]
No misunderstanding 🙂 Queries _can_ have several megabytes in size, e.g. a query

```
DELETE FROM some_table WHERE uuid IN (<62500 UUIDs with 32 bytes>)
```

... will have 2+ MB.

(It's not a question of whether it _should_ happen, but that it _can_ happen)

Or it could be just a simple `INSERT` with a data blob of megabytes in length.

The solution with regards to the clipboard copying could be to simply have some limit - for example 1+ MB queries won't be able to be copied. I just wanted to mention the possibility of such situations.

**Comment by LionelLaffineur** [comment]
@smuuf, you are totally right !  I didn't think about that (perhaps because, in my role of final user, I don't do that kind of queries).
Feel free to comment anything else, I'm always happy to get input/feedback, because there is more in a few millions brains than in one single ;-)
