### ISSUE TITLE
Timeout error: git submodule update --init

### ISSUE THREAD

**Issue by tobias992** [adminerevo/adminerevo#36]
When you run this command `git submodule update --init` you will get timeouts for:

github.com/vrana/JsShrink
github.com/vrana/jush

Problem is a wrong url in .gitmodules file. Just replace "git:" with "https:" and everything is fine again and you can use compile.php without errors.

**Comment by LionelLaffineur** [comment]
Thanks @tobias992. I have adjusted in main branch, it works well now.
