### ISSUE TITLE
Search 'regular expression' and 'LIKE%%' results reversed

### ISSUE THREAD

**Issue by Jim537** [adminerevo/adminerevo#37]
To reproduce:

Database: wordpress

Tables and views/Search data in tables

Search for 'db_'  

'as regular expression' - not ticked
returns results as 'regular expression' with the underscore matching any single character 

'as regular expression' - ticked
returns results as 'like%%'

**Comment by LionelLaffineur** [comment]
Hi @Jim537,
I'm not able to reproduce with my test databases.  Would you be able to post an export as SQL for me to test with you particular data ?
Tx

**Comment by Jim537** [comment]
Hi LionelLaffineur 

Thanks for taking a look.

Here are three files...

    wp.sql  - for import to create database
    wp_options_1.sql - results for 'db_' search with reg expr box not ticked
    wp_options_2.sql - results for 'db_' search with reg expr box ticked
    
I would expect the results to be reversed. 

[Downloads.zip](https://github.com/adminerevo/adminerevo/files/12209218/Downloads.zip)

**Comment by LionelLaffineur** [comment]
Dear @Jim537,
I did some tests and can't reproduce what you mention :

![Screenshot 2023-07-30 17 01 59](https://github.com/adminerevo/adminerevo/assets/21120913/0a501dbb-bade-4f0f-8c6b-906ea4f20c70)

![Screenshot 2023-07-30 17 03 16](https://github.com/adminerevo/adminerevo/assets/21120913/ca3aaccf-d25b-4bfe-b068-b2e745c5b180)

Searching "db_" as regular expression finds only in 1 table, where searching as LIKE %% finds in 2 tables.

![Screenshot 2023-07-30 17 05 37](https://github.com/adminerevo/adminerevo/assets/21120913/71453c1f-9554-4223-8a85-5d0763fc70eb)
To validate : I have executed a search in table 'customer' with regular expression, which has returned no result.

Did I not test what you expected ?

**Comment by Jim537** [comment]
Hi LionelLaffineur

Well this is strange. When you said you couldn't reproduce it I started looking further afield.

I found the same results using an online MYSQL compiler. Each search result is reproduced at https://onecompiler.com/mysql/3zg32x4ys  &   https://onecompiler.com/mysql/3zg34su49

So...
I have confirmation of my initial result - but am I wrong in some way ?
Adminer itself looks OK 
Why are you getting a different results - are you using MYSQL ?
There should be 6 results for regexpr and three results for non-regexpr

**Comment by LionelLaffineur** [comment]
There is here some useful reading about the LIKE operator and the _ character:
https://stackoverflow.com/questions/22167132/mysql-like-query-with-underscore

In summary : underscore is a special character that matches any single character.

I think, I hope you can find what you are looking for there.

**Comment by Jim537** [comment]
Hi LionelLaffineur

Thanks for that. I now see where I went wrong but I do think there is a point for discussion here.

Adminer has a basic search function now with a regexpr tick box.

It isn't clear that SQL rules apply here.

With a GUI interface like Adminer should these searches work more like a conventional word processor ?

If 'ab_' is entered for a basic search then shouldn't Adminer escape the '_' before doing the search so that only results with 'ab_' are returned. We should not get results with 'abc', 'abd', 'abe' etc.

If 'ab_' is entered for a regexp search then we should expect results containing 'ab_' , 'abc', 'abd', 'abe' etc. Not results only with 'ab_' as at present.

Be interested to see what you and others think.
