### ISSUE TITLE
Firefox "The byte stream was erroneous according to the character encoding that was declared. The character encoding declaration may be incorrect."

### ISSUE THREAD

**Issue by francoisjacquet** [adminerevo/adminerevo#53]
Hello,

I would like to report this error in the Firefox console:

![image](https://github.com/adminerevo/adminerevo/assets/4723501/5eff0f4c-23df-47a6-9a67-d75787a71df9)

The error happens on Firefox, not Chrome.

It also happens on a domain, no issue on localhost...

Here are some headers of the response for GET adminer.php
![image](https://github.com/adminerevo/adminerevo/assets/4723501/71f617da-9ee7-4a16-9e71-34a1752110de)

I have tried to encode the file to UTF-8, but this leads to other errors...

Please also note, I did not have this issue with adminer 4.8.1.

--Edit--
I do not have the issue with adminer 4.8.1 "English only"

**Comment by LionelLaffineur** [comment]
Dear @francoisjacquet, thanks for reporting this issue.
With my setup, which I use daily with both FF & Chrome, I don't have that kind of error in the console.
Could you write down which plugins / theme you are using and if possible : post a zip of your setup in order I can test it directly ?
Regards,
L.

**Comment by francoisjacquet** [comment]
Hello @francoisjacquet 

I use no plugins.
The theme is https://gitlab.com/francoisjacquet/adminer-theme-flat-ui

There must have been a cache issue, as there are no more errors now :)

Thank you.
