### ISSUE TITLE
Fatal error when I click 2nd or 3rd or 4th page(pagination)

### ISSUE THREAD

**Issue by ileadu** [adminerevo/adminerevo#62]
DB is SQL server. PHP 8.1
I found it's a bug of adminer, too.

Fatal error: Uncaught Error: Call to undefined method Min_PDOStatement::seek() in /home/vagrant/adminer/index.php:1777 Stack trace: #0 {main} thrown in /home/vagrant/adminer/index.php on line 1777

![image](https://github.com/adminerevo/adminerevo/assets/237095/1054d8be-2a1e-4ec8-be89-2f3c20323595)

**Comment by mckaygerhard** [comment]
hi please can you test agains new release? https://github.com/adminerevo/adminerevo/releases/tag/v4.8.4 thanks in advance

**Comment by ileadu** [comment]
I've tried again. Laravel Homestead is using pdo_dblib(default) to connect MS SQL Server.
I removed it and install sqlsrv and pdo_sqlsrv. I got another problem.

![image](https://github.com/adminerevo/adminerevo/assets/237095/049d5288-d864-4a0d-b402-f8bb4803018f)
[Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:self signed certificate] [Microsoft][ODBC Driver 18 for SQL Server]Client unable to establish connection. For solutions related to encryption errors, see https://go.microsoft.com/fwlink/?linkid=2226722

How to set TrustServerCertificate to 'Yes'?

**Comment by ileadu** [comment]
https://www.php.net/manual/en/function.sqlsrv-connect
https://learn.microsoft.com/en-us/sql/connect/php/connection-options?view=sql-server-ver16&redirectedfrom=MSDN


TrustServerCertificate
![image](https://github.com/adminerevo/adminerevo/assets/237095/2f1b689d-4b8a-4d68-84ef-5e7fd9d9a395)

![image](https://github.com/adminerevo/adminerevo/assets/237095/a0e90e53-ed39-4a6c-85a9-daf5e0916ab0)

**Comment by ileadu** [comment]
$connection_info = array("UID" => $username, "PWD" => $password, "CharacterSet" => "UTF-8", 'TrustServerCertificate' => 1);
Added this option and re-compiled. It's okay.
![image](https://github.com/adminerevo/adminerevo/assets/237095/1ff10e47-550c-4544-8a63-aa5470e01e27)

**Comment by mckaygerhard** [comment]
ok this issue is solved and must be closed as comment https://github.com/adminerevo/adminerevo/issues/62#issuecomment-2175539605 suggests  @LionelLaffineur 

i'll open a new issue/pullrequest about the m$ crap database connection error, the issue of m$ crap database in https://github.com/adminerevo/adminerevo/issues/62#issuecomment-2174792844 can be solved as you @ileadu  suggested in comment https://github.com/adminerevo/adminerevo/issues/62#issuecomment-2175539605

Thanks for all!
