### ISSUE TITLE
Different colors for true and false

### ISSUE THREAD

**Issue by OmlineEditor** [adminerevo/adminerevo#66]
I often work with data that is of type true-false. for a better perception and understanding of the table, I ask you to make the display of these variables colored

![color](https://github.com/adminerevo/adminerevo/assets/13348933/a56bac6f-1821-43e9-8096-8b082d71336d)

**Comment by LionelLaffineur** [comment]
I think this should be done via a theme better than a core feature.

**Comment by OmlineEditor** [comment]
> What data type is the column containing true and false?

the data is of boolean type, there are only two values true and false. Why is this type highlighted in the program as the 'code' type and has a gray background.

**Comment by hjsleijster** [comment]
That's a fair point. I can't recreate a table with boolean, because I only have mysql, which doesn't support the boolean type.

What about:
`<code class="boolean-true">t</code>`
or
`<code data-boolean="true">t</code>`

**Comment by aoirthoir** [comment]
I am not sure how this affects this conversation or Adminerevo in regards to display of Booleans but:

> You can use BIT data type to store boolean data (like on T-SQL / SQL Server):
> 
> ```mysql
> CREATE TABLE `table_name` (
>     `column_name` BIT(1)
> );
> ```
> 
> On MySQL the data types BOOL and BOOLEAN are also available:
> 
> ```mysql
> CREATE TABLE `table_name` (
>     `column_name1` BOOL,
>     `column_name2` BOOLEAN
> );
> ```
> 
> The BOOL and BOOLEAN data types are synonyms for TINYINT(1):
> 
> These types (BOOL and BOOLEAN) are synonyms for TINYINT(1). A value of zero is considered false. Nonzero values are considered true.
