### ISSUE TITLE
source tarball missing externals

### ISSUE THREAD

**Issue by niol** [adminerevo/adminerevo#69]
I'm looking to include adminerevo in Debian instead of adminer.

Provided source packages lack externals (JsShrink and jush) and thus adminer.php cannot be build without using git and pull submodules. Would it be possible to provide a full source tarball? The alternative for me is to package those files as external dependencies.

Please advise what works for everybody.

**Comment by devinemke** [comment]
@niol  Is it necessary to have the full source/repo as part of your distro? Rather than the single complied **.php** file? I ask because there are pre-complied versions of AdminerEvo at **https://download.adminerevo.org** for various db drivers and languages.

**Comment by niol** [comment]
To put it short, everything going into Debian must compiled from source (to make it possible to fix things even if upstream software websites disappear), this means no precompiled stuff.
Anyway, I worked around this, so this is not an issue anymore for me.
