### ISSUE TITLE
Make is_url function clickable for local network domains or IPs

### ISSUE THREAD

**Issue by nitodico** [adminerevo/adminerevo#7]
I post it here because the original Adminer project seems pretty abandoned, hope this one born again from the ashes

The `is_url` function make clickable only any http://domain.com/ values, but it doesnt accepts IP such http://192.168.0.69/ or local hostname such http://mylocalserver/

**Comment by nitodico** [comment]
My bad, issue with IP links seems to work where last digits are 2 o3 long like 192.168.0.0.**56** or 192.1680.0.**110**, but doesnt works with 192.168.0.**1** or 192.168.0.**9**

**Comment by LionelLaffineur** [comment]
Thanks a lot for your contribution !
It is well appreciated.
