### ISSUE TITLE
Editor: left column missing descriptive table names

### ISSUE THREAD

**Issue by iiidefix** [adminerevo/adminerevo#70]
![image](https://github.com/adminerevo/adminerevo/assets/1006288/29a73c19-e2f1-4bff-a1fa-93a968a14dc6)

Compared to regular adminer the editor is missing descriptive table names in the left column. 
This is caused by omitting the `Show structure` anchors, that show that table name. Which is completely fine and works as intended, as they are not relevant in editor. 
But a visible table name would be helpful.

Relevant code:
Adminer: https://github.com/adminerevo/adminerevo/blob/ae0d5ebf1739d17460d2ee5457d6e33e4bf847b9/adminer/include/adminer.inc.php#L1080-L1089

Editor: https://github.com/adminerevo/adminerevo/blob/ae0d5ebf1739d17460d2ee5457d6e33e4bf847b9/editor/include/adminer.inc.php#L624-L627

**Comment by LionelLaffineur** [comment]
Dear @iiidefix,
I have no ready-to-use setup to debug and fix your issue.  Would you be able to attach to this issue something I could use ? (including a test database for mysql if possible)
Regards,
L.

**Comment by iiidefix** [comment]
Hi @LionelLaffineur,

this is a database independent issue. So any database will work.

For example this simple one (second table is also optional):

```SQL
SET NAMES utf8mb4;

CREATE DATABASE `test` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `test`;

CREATE TABLE `test` (
  `test` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `test2` (
  `test` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```

Simply open any database in adminer editor and you see something similar to the screenshot above. A select icon for each table but no table name.

The second echo in the above mentioned `/adminer/include/adminer.inc.php` is crating the visible table name output that is missing in `editor.php`
The `'>$name</a>` in `editor.php` is not visible because of a `font-size: 0` (and some margin to make the icon look nice) in  css class `select` (`#tables li a.select`).

Regards,
iiidefix

**Comment by LionelLaffineur** [comment]
Fix via this commit https://github.com/adminerevo/adminerevo/commit/7fdcb922e1a1a21d33f6b1889427642581474f1f.
Thanks for reporting the issue !
