### ISSUE TITLE
PHP 8.3 [Warning: Trying to access array offset on null in adminer-4.8.3\adminer-4.8.3.php on line 1491]

### ISSUE THREAD

**Issue by thyjacksparrow** [adminerevo/adminerevo#80]
I am getting below mentioned Warning
Warning: Trying to access array offset on null in adminer-4.8.3\adminer-4.8.3.php on line 1491

**Comment by petrovo-as** [comment]
4.8.4-dev ....  Warning Add foreign key
Warning: Trying to access array offset on null in adminer.php on line 1716
![2024-01-18_10-02-02](https://github.com/adminerevo/adminerevo/assets/85673933/3f476024-f3ab-4b3b-b70f-69fa04c771d2)

**Comment by Sergiobop** [comment]
Yeah, this warning is annoying

**Comment by ChristopheTesconi** [comment]
Hi, How we can resolve it ? I'm looking for a solution without success so far.

**Comment by gamgamstylep** [comment]
Have a similiar problem
![2024-02-24 10_59_09-Daten zeigen von_ ALL_PLUGINS - db1 - Adminer](https://github.com/adminerevo/adminerevo/assets/43586166/1e8050ef-e573-43c2-afe5-82f7e50ac0f1)

**Comment by mckaygerhard** [comment]
this error is not happened in 4.,9 but now creatinon of DB with mysql 8.0 is not possible:

2 - Undefined array key 1 - /usr/share/adminer/adminer-4.9.0.php:1693 2 - Undefined array key 1 - /usr/share/adminer/adminer-4.9.0.php:1693

2 - Undefined array key "add_x" - /usr/share/adminer/adminer-4.9.0.php:1696 2 - Undefined array key "collation" - /usr/share/adminer/adminer-4.9.0.php:1696
[?](https://dev.mysql.com/doc/refman/8.0/en/charset-charsets.html) 2 - Undefined array key "add_x" - /usr/share/adminer/adminer-4.9.0.php:1697 2 - Undefined array key "db" - /usr/share/adminer/adminer-4.9.0.php:1697

![image](https://github.com/adminerevo/adminerevo/assets/1571724/b9f77986-064c-4122-872d-29ddbadc4088)

**Comment by paulalbertdev** [comment]
Got the same warnings here !

**Comment by kooshal** [comment]
Same issue 
<img width="788" alt="image" src="https://github.com/adminerevo/adminerevo/assets/473956/949da031-2a64-4b66-a6b3-026554c41afd">

**Comment by andersmmg** [comment]
Same error, it makes some parts of the ui unusable

**Comment by mckaygerhard** [comment]
the problem is the constant changes of fucking enterprices and stupid developers... adminerevo was working great until we ugraded to mysql 8.X

**Comment by alxndr-w** [comment]
closed with https://github.com/adminerevo/adminerevo/releases/tag/v4.8.4

> the problem is the constant changes of fucking enterprices and stupid developers... adminerevo was working great until we ugraded to mysql 8.X

wtf? No. These warnings became **visible** with PHP 8.3 - it's Adminer that wasn't updatet for a long time and I'm happy to see that AdminerEvo exists.

**Comment by sherriff93** [comment]
I think I have found a solution to this? Seems like this warning was already being raised but then being suppressed in the adminer.php script. However it was being suppressed via a text match, and the text content of the warning has changed in one of the latest PHP updates (Probably 8.3).

To fix, try opening up the source code and changing:

`'~^(Trying to access array offset on value of type null|Undefined array key)~'` (was on line 10 for me in a `preg_match(...)`, just before the only usage of `error_reporting`.

to:

`'~^(Trying to access array offset on null|Undefined array key)~'`

This seemed to work for me!

**Comment by feedlead** [comment]
> **[sherriff93](/sherriff93) ** comment

This worked perfect!

**Comment by User-425** [comment]
> @sherriff93 comment
I'm using Adminer, and this works for me.

**Comment by mckaygerhard** [comment]
i confirmed too, please someone that commit this patch to the repository?

@LionelLaffineur you marked as solved but seems some people posted that this works.. and is a easy to commit fix! thanks in advance
