### ISSUE TITLE
PHP 8.3: Trying to access array offset on null in compile.php on line 254

### ISSUE THREAD

**Issue by devinemke** [adminerevo/adminerevo#88]
**Environment:** 
macOS 13.6.2
Apache 2.4.58
MySQL 8.2.0
PHP 8.3.0

When running `php compile.php mysql en` I get the following error:
`Trying to access array offset on null in /adminerevo/compile.php on line 254`

compile.php line 254:
`if ($tokens[$i+2][0] === T_CLOSE_TAG && $tokens[$i+3][0] === T_INLINE_HTML && $tokens[$i+4][0] === T_OPEN_TAG`

Might this be related to how PHP 8.3 now handles Increment/Decrement operators as described [here](https://www.php.net/manual/en/migration83.deprecated.php) ?:

> Using the [increment](https://www.php.net/manual/en/language.operators.increment.php) operator (++) on empty, non-numeric, or non-alphanumeric strings is now deprecated. Moreover, incrementing non-numeric strings is soft deprecated. That means no **E_DEPRECATED** diagnostic is emitted, but this feature should not be used when producing new code. The new [str_increment()](https://www.php.net/manual/en/function.str-increment.php) function should be used instead.

**Comment by Lumeriol** [comment]
Probably it could be resolved by [this](https://github.com/vrana/adminer/pull/484/commits/244aa0c1e6d443e00664dd97dc79a0a62918534d) pull request in original library.

@LionelLaffineur would it be possible to drag and drop and implement?

**Comment by devinemke** [comment]
@Lumeriol I can confirm that [**this AdminerEvo PR**](https://github.com/adminerevo/adminerevo/pull/106) (which appears to be the same change as [**this Adminer PR**](https://github.com/vrana/adminer/pull/484)) does **_not_** fix this issue (still getting the same error at line 254 when running `php compile.php mysql en` when this change is applied).

**Comment by devinemke** [comment]
fixed with this [**merged PR**](https://github.com/adminerevo/adminerevo/pull/106). thanks.
