### ISSUE TITLE
Editor - invisible menu text

### ISSUE THREAD

**Issue by otoman** [adminerevo/adminerevo#97]
In Adminer Editor is not visibile menu text.
Problem is in CSS `#tables li a.select {font-size:0;}`

![image](https://github.com/adminerevo/adminerevo/assets/297570/ce9e7a6b-ff72-4231-b627-e8c130466f0d)

**Comment by LionelLaffineur** [comment]
Dear @otoman, thanks for reporting this issue.

I have fixed it already, but I don't remember in which version:

![image](https://github.com/adminerevo/adminerevo/assets/21120913/d02b50e2-f620-42c8-93a5-560d0901cd5b)

Could be it is still in dev.  Feel free to test it by using the latest commit.

Regards,
L.

**Comment by otoman** [comment]
Dear LionelLaffineur,
sorry, I didn't notice. Thanks for your work.

Regards,
otoman
